spring:
  application:
    name: board2 # ??????
  datasource: # ?????? ????
    url: jdbc:mysql://localhost:3306/board2
    username: root
    password: green502

mybatis:  # Mybatis ??
  mapper-locations: mappers/**/*.xml # xml ????
